name: Draft Release

on:
  push:
    branches: [main]
    paths-ignore: ["**/CHANGELOG.md"]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  draft:
    uses: coyotito-mx/.github/.github/workflows/release-drafter.yml@main
    secrets:
      PAT: ${{ secrets.GITHUB_TOKEN }}
